apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aks
  annotations:
    meta.crossplane.io/maintainer: The Getting Started Organization <support@starter.org>
    meta.crossplane.io/source: github.com/upbound/configuration-aks
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This Azure starter configuration offers Kubernetes Clusters backed by AKS.
    meta.crossplane.io/readme: |
      This Configuration bundles an API definition. The API will 
      allow control planes to provision fully
      configured Azure Kubernetes Service (AKS) clusters, composed
      using cloud service primitives from the [Upbound Official Azure
      Provider family](https://marketplace.upbound.io/providers/upbound/provider-family-azure).
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
    - provider: xpkg.dev-deba7a0e.u6d.dev/upbound/provider-azure
      version: v0.0.2-annotated
